controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    controllers:
      - diff_drive_controller
      - joint_state_broadcaster
      - arm_position_controller

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel"]
    right_wheel_names: ["right_wheel"]
    wheel_separation: 0.53
    wheel_radius: 0.1
    publish_rate: 50
    command_interfaces: ["velocity"]
    state_interfaces: ["position", "velocity"]
    use_stamped_vel: false
    enable_odom_tf: true
    base_frame_id: base_link
    odom_frame_id: odom

joint_state_broadcaster:
  ros__parameters: {}

arm_position_controller:
  ros__parameters:
    joints:
      - torso_0
      - torso_1
      - torso_2
      - torso_3
      - torso_4
      - torso_5
      - right_arm_0
      - right_arm_1
      - right_arm_2
      - right_arm_3
      - right_arm_4
      - right_arm_5
      - right_arm_6
      - left_arm_0
      - left_arm_1
      - left_arm_2
      - left_arm_3
      - left_arm_4
      - left_arm_5
      - left_arm_6
      - head_0
      - head_1
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity