diff_drive_controller:
  ros__parameters:

    left_wheel_names: ["left_wheel"]
    right_wheel_names: ["right_wheel"]

    wheel_separation: 0.53
    wheel_radius: 0.1

    publish_rate: 50

    command_interfaces: ["velocity"]
    state_interfaces: ["position", "velocity"]

    use_stamped_vel: false
    enable_odom_tf: true

    base_frame_id: base_link
    odom_frame_id: odom
