publisher_joint_trajectory_controller:
  ros__parameters:

    controller_name: "joint_trajectory_controller_left_arm"
    wait_sec_between_publish: 6

    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    pos1:
      positions: [0.785, 0.0, 0.785, 0.0, 0.785 , 0.0, 0.785]
    pos2:
      positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    pos3:
      positions: [0.785, 0.0, 0.785, 0.0, 0.785 , 0.0, 0.785]
    pos4:
      positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    joints:
      - left_arm_0
      - left_arm_1
      - left_arm_2
      - left_arm_3
      - left_arm_4
      - left_arm_5
      - left_arm_6

    check_starting_point: false
    # starting_point_limits:
    #   joint1: [-0.1,0.1]
    #   joint2: [-0.1,0.1]